### ISSUE TITLE
Implement Reader function for Stay Open

### ISSUE THREAD

**Issue by evanoberholster** [mostlygeek/go-exiftool#10]
I admire your code and the effort you put into it. I am working on a project that needs to read from a Reader instead of a File. For performance reasons I prefer to use the Stay Open methods.

I have tried implementing this and it doesn't seem to work.

Searching I found this on the exiftool forum, so it should work correctly:
http://u88.n24.queensu.ca/exiftool/forum/index.php?topic=3664.0
I am implementing on Linux/MacOS.

Below is my code, any suggestions or ideas?

Thanks

```Golang
 func (e *Stayopen) ExtractReaderFlags(source io.Reader, flags ...string) ([]byte, error) {
	e.l.Lock()
	defer e.l.Unlock()

	if e.cmd == nil {
		return nil, errors.New("Stopped")
	}

	// send the request
	fmt.Fprintln(e.stdin, e.defaultFlags)
	if len(flags) > 0 {
		//fmt.Fprintln(e.stdin, strings.Join(flags, "\n"))
	}
       // Send Flag
	fmt.Fprintln(e.stdin, "-")

       // OPTION 1:
       // io.Copy(e.stdin, source)

       // OPTION 2:
	fmt.Fprintln(e.stdin, source)

       // Execute
	fmt.Fprintln(e.stdin, "-execute")

	if !e.scanner.Scan() {
		return nil, errors.New("Failed to read output")
	} else {
		results := e.scanner.Bytes()
		sendResults := make([]byte, len(results), len(results))
		copy(sendResults, results)
		return sendResults, nil
	}
}
```

**Comment by mostlygeek** [comment]
Did you figure this out yourself?  I didn't get notifications because I wasn't watching my own repo... 

I'm not sure how to accomplish what you asked for since `stdin` is used to send exiftool control information.  If you send it a bunch of binary data (your image) it probably wouldn't know how to deal with that.  The forum post you linked (I didn't read it all) seems like it was asking how to send exiftool commands via stdin instead of using the argFile (a text file with all the commands). 

You can use the [ExtractReader](https://godoc.org/github.com/mostlygeek/go-exiftool#ExtractReader) method if you want to use an io.Reader.   This method sucks because it sends *all* the data to exiftool.  This can be slow and it might negate all speed ups you get using stayopen. 

exiftool is able to extract metadata without reading the whole file.  So it might be faster for you to write the whole file to disk and then use exiftool w/ stayopen at your temporary file.

**Comment by mostlygeek** [comment]
closing this issue as it is impossible to use stayopen and send image data to stdin.
